### ISSUE TITLE
Dummy question about input format

### ISSUE THREAD

**Issue by jmny** [karepker/little-tsp#2]
Hello,

I don't understand the input file's vertex list definition, I see other program using a matrix format , like : (here a symetric case) : 

 (Distance from 0 to 1 is 1.0, 1 to 2 is 3.0, 0 to 2 is 2.0)
D = [[ 0, 1.0, 2.0],
     [ 1.0, 0, 3.0],
     [ 2.0, 3.0, 0]]

and i understand this format.

Could you help me to understand your format ?

Regards,

**Comment by karepker** [comment]
The input elements are coordinates on some square map. The distance between each pair of vertices is equal to their [taxicab (Manhattan) distance](https://en.wikipedia.org/wiki/Taxicab_geometry). Every vertex is considered connected to every other vertex. I.e. the input is interpreted as a complete graph.

**Comment by jmny** [comment]
thank you :)
